name: ministate
description: | 
  Minimalistic State Management 
  using get_it as a service locator and the built in ValueNotifier to 
  manage state in a flutter application

version: 0.0.4
homepage: https://github.com/deicon/flutter_mini_state
repository: https://github.com/deicon/flutter_mini_state


environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.3
  get_it: ^7.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:

